### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by BrunoCartier** [FOGProject/website#2]
http://downforeveryoneorjustme.com/fogproject.org

**Comment by jbob182** [comment]
We are in the middle of transferring to another server. I'll close this issue once we finish.

**Comment by BrunoCartier** [comment]
Ok, nice, I was scared that the domain name was hijacked or something like that :)

**Comment by jbob182** [comment]
It should be coming back online slowly (dns was just updated so it could take a little while for all of the dns servers to update).
